

export const AUDIO_KEYS = Object.freeze({
  bossCoreShutdownClean: "boss_core_shutdown_clean",
  bossDeathPulse1Clean: "boss_death_pulse_1_clean",
  bossDeathPulse2Clean: "boss_death_pulse_2_clean",
  bossDeathPulse3Clean: "boss_death_pulse_3_clean",
  bossDeathPulse4Clean: "boss_death_pulse_4_clean",
  bossIntroReactorWakeClean: "boss_intro_reactor_wake_clean",
  bossLandingImpactClean: "boss_landing_impact_clean",
  bossMachineBedPhase1Clean: "boss_machine_bed_phase_1_clean",
  bossMachineBedPhase2Clean: "boss_machine_bed_phase_2_clean",
  bossMachineBedPhase3Clean: "boss_machine_bed_phase_3_clean",
  bossPhaseOverloadClean: "boss_phase_overload_clean",
  destructionChargeClean: "destruction_charge_clean",
  destructionFireClean: "destruction_fire_clean",
  droneBombExplosionClean: "drone_bomb_explosion_clean",
  droneBombFallClean: "drone_bomb_fall_clean",
  droneLockingBeepClean: "drone_locking_beep_clean",
  droneLockingBeepLoopClean: "drone_locking_beep_loop_clean",
  gravityCollapseClean: "gravity_collapse_clean",
  gravityLoopClean: "gravity_loop_clean",
  gravityStartClean: "gravity_start_clean",
  laserChargeClean: "laser_charge_clean",
  laserFireClean: "laser_fire_clean",
  menacingChargeClean: "menacing_charge_clean",
  menacingDashClean: "menacing_dash_clean",
  oldBroadcastWarningClean: "old_broadcast_warning_clean",
  playerBlinkClean: "player_blink_clean",
  playerDashClean: "player_dash_clean",
  playerHurtClean: "player_hurt_clean",
  treeBarrierBreakClean: "tree_barrier_break_clean",
  treeBarrierRaiseClean: "tree_barrier_raise_clean",
  tumieAftershockClean: "tumie_aftershock_clean",
  tumieCutImpactClean: "tumie_cut_impact_clean",
  tumieExecutionChargeClean: "tumie_execution_charge_clean",
  tumieServoWarningClean: "tumie_servo_warning_clean",
  turretDeployClean: "turret_deploy_clean",
  turretDestroyClean: "turret_destroy_clean",
  turretShotClean: "turret_shot_clean",
});

export const AUDIO_MANIFEST = Object.freeze([
  { key: "boss_core_shutdown_clean", path: "assets/audio/boss_core_shutdown_clean.wav", category: "boss_death" },
  { key: "boss_death_pulse_1_clean", path: "assets/audio/boss_death_pulse_1_clean.wav", category: "boss_death" },
  { key: "boss_death_pulse_2_clean", path: "assets/audio/boss_death_pulse_2_clean.wav", category: "boss_death" },
  { key: "boss_death_pulse_3_clean", path: "assets/audio/boss_death_pulse_3_clean.wav", category: "boss_death" },
  { key: "boss_death_pulse_4_clean", path: "assets/audio/boss_death_pulse_4_clean.wav", category: "boss_death" },
  { key: "boss_intro_reactor_wake_clean", path: "assets/audio/boss_intro_reactor_wake_clean.wav", category: "boss_skill" },
  { key: "boss_landing_impact_clean", path: "assets/audio/boss_landing_impact_clean.wav", category: "boss_skill" },
  { key: "boss_machine_bed_phase_1_clean", path: "assets/audio/boss_machine_bed_phase_1_clean.wav", category: "boss_bed", loop: true },
  { key: "boss_machine_bed_phase_2_clean", path: "assets/audio/boss_machine_bed_phase_2_clean.wav", category: "boss_bed", loop: true },
  { key: "boss_machine_bed_phase_3_clean", path: "assets/audio/boss_machine_bed_phase_3_clean.wav", category: "boss_bed", loop: true },
  { key: "boss_phase_overload_clean", path: "assets/audio/boss_phase_overload_clean.wav", category: "boss_skill" },
  { key: "destruction_charge_clean", path: "assets/audio/destruction_charge_clean.wav", category: "boss_skill" },
  { key: "destruction_fire_clean", path: "assets/audio/destruction_fire_clean.wav", category: "boss_skill" },
  { key: "drone_bomb_explosion_clean", path: "assets/audio/drone_bomb_explosion_clean.wav", category: "boss_skill" },
  { key: "drone_bomb_fall_clean", path: "assets/audio/drone_bomb_fall_clean.wav", category: "boss_skill" },
  { key: "drone_locking_beep_clean", path: "assets/audio/drone_locking_beep_clean.wav", category: "boss_skill" },
  { key: "drone_locking_beep_loop_clean", path: "assets/audio/drone_locking_beep_loop_clean.wav", category: "boss_skill_loop", loop: true },
  { key: "gravity_collapse_clean", path: "assets/audio/gravity_collapse_clean.wav", category: "boss_skill" },
  { key: "gravity_loop_clean", path: "assets/audio/gravity_loop_clean.wav", category: "boss_skill_loop", loop: true },
  { key: "gravity_start_clean", path: "assets/audio/gravity_start_clean.wav", category: "boss_skill" },
  { key: "laser_charge_clean", path: "assets/audio/laser_charge_clean.wav", category: "boss_skill" },
  { key: "laser_fire_clean", path: "assets/audio/laser_fire_clean.wav", category: "boss_skill" },
  { key: "menacing_charge_clean", path: "assets/audio/menacing_charge_clean.wav", category: "boss_skill" },
  { key: "menacing_dash_clean", path: "assets/audio/menacing_dash_clean.wav", category: "boss_skill" },
  { key: "old_broadcast_warning_clean", path: "assets/audio/old_broadcast_warning_clean.wav", category: "system" },
  { key: "player_blink_clean", path: "assets/audio/player_blink_clean.wav", category: "player_disabled" },
  { key: "player_dash_clean", path: "assets/audio/player_dash_clean.wav", category: "player_disabled" },
  { key: "player_hurt_clean", path: "assets/audio/player_hurt_clean.wav", category: "player_disabled" },
  { key: "tree_barrier_break_clean", path: "assets/audio/tree_barrier_break_clean.wav", category: "player_ability" },
  { key: "tree_barrier_raise_clean", path: "assets/audio/tree_barrier_raise_clean.wav", category: "player_ability" },
  { key: "tumie_aftershock_clean", path: "assets/audio/tumie_aftershock_clean.wav", category: "boss_skill" },
  { key: "tumie_cut_impact_clean", path: "assets/audio/tumie_cut_impact_clean.wav", category: "boss_skill" },
  { key: "tumie_execution_charge_clean", path: "assets/audio/tumie_execution_charge_clean.wav", category: "boss_skill" },
  { key: "tumie_servo_warning_clean", path: "assets/audio/tumie_servo_warning_clean.wav", category: "boss_skill" },
  { key: "turret_deploy_clean", path: "assets/audio/turret_deploy_clean.wav", category: "boss_skill" },
  { key: "turret_destroy_clean", path: "assets/audio/turret_destroy_clean.wav", category: "boss_skill" },
  { key: "turret_shot_clean", path: "assets/audio/turret_shot_clean.wav", category: "boss_skill" },
]);

export function loadDeadPortSfx(scene) {
  for (const item of AUDIO_MANIFEST) {
    scene.load.audio(item.key, item.path);
  }
}

export default AUDIO_KEYS;
